global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000']
  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:9000']
